### ISSUE TITLE
Feel free to nab

### ISSUE THREAD

**Issue by NickCH-K** [haghish/machinelearning#1]
I imagine you've already seen it with your **rcall** GitHub search in the slides, but I have a package **MLRtime** which is also designed for running machine learning methods from Stata using `rcall`. `ranger::ranger()` and `grf::causal_forest()` are implemented. I'm not currently planning to expand it, though. So feel free to nab any code you'd like if you want to incorporate those two.

**Comment by haghish** [comment]
Thanks Nick. I'm actually not planning on writing a machine learning package. I'm working on a tutorial SJ paper, demonstrating lots of tricks that can be done with `rcall`.  Your package seems very promising though! Why not working further on it and getting it on Stata Journal?

**Comment by NickCH-K** [comment]
Hmm, I hadn't considered the possibility of it going to SJ, maybe that's enough incentive to expand it. And good to know, thanks!

**Comment by haghish** [comment]
welcome! And I can tell that the topic is highly of interest of SJ! cheers.

**Comment by NickCH-K** [comment]
I have already done some expansions and will be doing more! Thanks for the nudge.

**Comment by haghish** [comment]
excellent news! And if you think your package can also be introduced in a tutorial paper, we could have some collaboration chances, which I welcome! my email is haghish@uio.no if that idea sounds interesting to you.
