### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by emawbgit** [haghish/machinelearning#2]
Hi, I get this error while installing machinelearning. Any hint? Thanks 
![image](https://user-images.githubusercontent.com/65594313/226839890-a8a5a8f3-70a0-40a8-88bb-34200297851c.png)

**Comment by haghish** [comment]
there was a problem in the installation file. will be fixed in a day

**Comment by emawbgit** [comment]
[like]  Emanuele Clemente reacted to your message:
________________________________
